backend:
  name: git-gateway
  # branch: dev 
local_backend: true
media_folder: 'assets/img'
collections:
  - label: "Data"
    name: "_data"
    files:
      - label: "About"
        name: "about"
        file: "_data/about.yml"
        fields:
          - label: "Poza"
            name: "image"
            widget: "image"
            choose_url: false
            media_library:
              config:
                multiple: false
          - label: "Date"
            name: "fork"
            widget: "string"
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Description", name: "description", widget: "markdown" }