backend:
  name: git-gateway
  # branch: dev 
local_backend: true
media_folder: 'assets/img'
collections:
  - label: "Data"
    name: "data"
    files:
      - label: "About"
        name: "about"
        file: "data/about.yml"
        fields:
          - label: "Poza"
            name: "image"
            widget: "image"
            choose_url: false
            required: true
            media_library:
              config:
                multiple: false
          - label: "Date"
            name: "fork"
            widget: "string"
            type: string
            required: true
          - label: "Title"
            name: "title"
            widget: "string"
            type: string
            required: true
          - label: "Description"
            name: "description"
            widget: "markdown"
            required: false