backend:
  name: git-gateway
  # branch: dev 
local_backend: true
media_folder: 'assets/img'
collections:
  - label: "About"
    name: "about"
    files:
      - label: "About Page"
        name: "about"
        file: "_data/about.yml"
        fields:
          - { label: 'Poza', name: 'image', widget: image, allow_multiple: false}
          - {label: Data, name: fork, widget: string}
          - {label: Title, name: title, widget: string}
          - {label: Description, name: description, widget: markdown}